"""Initial migration

Revision ID: 55475cd1c3f0
Revises:
Create Date: 2025-08-20 16:38:37.131735

"""
from typing import Sequence, Union

# fmt: off
from alembic import op  # noqa
import sqlalchemy as sa  # noqa
import sqlmodel  # EDITED  # noqa
from sqlalchemy.dialects import postgresql
# fmt: on

# revision identifiers, used by Alembic.
revision: str = '55475cd1c3f0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column(
                        'email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.Column('role', sa.VARCHAR(), nullable=False),
                    sa.Column('is_verified', sa.Boolean(), nullable=False),
                    sa.Column('password_hash',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(
                        timezone=True), nullable=True),
                    sa.Column('modified_at', postgresql.TIMESTAMP(
                        timezone=True), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
