"""add_permissions

Revision ID: 2a3c5c4c0a33
Revises: 9914df272fc1
Create Date: 2025-09-11 21:51:14.772102

"""
from typing import Sequence, Union
# fmt: off
from alembic import op  # noqa
import sqlalchemy as sa  # noqa
import sqlmodel  # EDITED  # noqa
from sqlalchemy.dialects import postgresql
# fmt: off

# revision identifiers, used by Alembic.
revision: str = '2a3c5c4c0a33'
down_revision: Union[str, Sequence[str], None] = '9914df272fc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('resource', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('context', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
                    sa.Column('modified_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
                    sa.PrimaryKeyConstraint('id'))
    op.create_index(op.f('ix_permissions_resource'), 'permissions', ['resource'], unique=False)

    op.create_table('role_permissions',
                    sa.Column('role_id', sa.Integer(), nullable=False),
                    sa.Column('permission_id', sa.Integer(), nullable=False),
                    sa.Column('assigned_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
                    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
                    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
                    sa.PrimaryKeyConstraint('role_id', 'permission_id'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_permissions_resource'), table_name='permissions')
    op.drop_table('permissions')
    # ### end Alembic commands ###
